merged with r buildpack

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,28 +1,108 @@
-#!/usr/bin/env ruby
-# Encoding: utf-8
-# IBM WebSphere Application Server Liberty Buildpack
-# Copyright 2013-2014 the original author or authors.
-#
-# Licensed under the Apache License, Version 2.0 (the "License");
-# you may not use this file except in compliance with the License.
-# You may obtain a copy of the License at
-#
-#      http://www.apache.org/licenses/LICENSE-2.0
-#
-# Unless required by applicable law or agreed to in writing, software
-# distributed under the License is distributed on an "AS IS" BASIS,
-# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
-# See the License for the specific language governing permissions and
-# limitations under the License.
+#!/usr/bin/env bash
+# bin/compile <build-dir> <cache-dir>
 
-$stdout.sync = true
-$stderr.sync = true
-$LOAD_PATH.unshift File.expand_path('../../lib', __FILE__)
+# fail fast
+set -e
 
-require 'liberty_buildpack/buildpack'
+# debug
+# set -x
 
-build_dir = ARGV[0]
+shopt -s extglob
 
-LibertyBuildpack::Buildpack.initialize_env(ARGV[2]) unless ARGV[2].nil?
+function error() {
+  echo " !     $*" >&2
+  exit 1
+}
 
-LibertyBuildpack::Buildpack.drive_buildpack_with_logger(build_dir, 'Compile failed with exception %s') { |buildpack| buildpack.compile }
+function indent() {
+  c='s/^/       /'
+  case $(uname) in
+    Darwin) sed -l "$c";;
+    *)      sed -u "$c";;
+  esac
+}
+
+# clean up leaking environment
+unset GIT_DIR
+
+# parse and derive params
+BUILD_DIR=$1
+CACHE_DIR="$2/vendor"
+LP_DIR=`cd $(dirname $0); cd ..; pwd`
+BUILDPACK_DIR="$(dirname $(dirname $0))"
+
+# config
+R_VERSION="3.1.0"
+BUILD_PACK_VERSION="20140608-1824"
+
+S3_BUCKET="heroku-buildpack-r"
+R_BINARIES="http://${S3_BUCKET}.s3.amazonaws.com/R-${R_VERSION}-binaries-${BUILD_PACK_VERSION}.tar.gz"
+
+VENDOR_DIR="$BUILD_DIR/vendor"
+R_BASE="$VENDOR_DIR/R"
+CRAN_MIRROR="http://cran.revolutionanalytics.com"
+
+mkdir -p $CACHE_DIR
+
+# vendor R into the slug
+echo "Vendoring R $R_VERSION" | indent
+
+# download and unpack binaries
+echo "Downloading and unpacking R binaries" | indent
+mkdir -p $VENDOR_DIR && curl $R_BINARIES -s -o - | tar xzf - -C $VENDOR_DIR
+
+# need to copy the binaries to /app/vendor so that R works
+mkdir -p /app/vendor/gcc
+cp -R $VENDOR_DIR/gcc/* /app/vendor/gcc
+
+mkdir -p /app/vendor/glibc
+cp -R $VENDOR_DIR/glibc/* /app/vendor/glibc
+
+mkdir -p /app/vendor/gsl
+cp -R $VENDOR_DIR/gsl/* /app/vendor/gsl
+
+mkdir -p /app/vendor/R
+cp -R $VENDOR_DIR/R/* /app/vendor/R
+
+# HACK: need to copy over the gcc libs so that packages can find them
+mkdir -p /app/vendor/R/lib64/R/lib
+cp /app/vendor/gcc/lib64/* /app/vendor/R/lib64/R/lib
+
+# R needs to know where gfortran and glibc header files are
+export PATH="/app/vendor/R/bin:/app/vendor/gcc/bin:$PATH"
+
+export LDFLAGS="-L/app/vendor/gcc/lib64 -L/app/vendor/gsl/lib"
+export CPPFLAGS="-I/app/vendor/glibc/string -I/app/vendor/glibc/time -I/app/vendor/gsl/include"
+export PKG_LDFLAGS=$LDFLAGS
+export PKG_CPPFLAGS=$CPPFLAGS
+
+export R_HOME=$R_BASE/lib64/R
+export R_INCLUDE=$R_HOME/include
+
+# copy over environment
+mkdir -p $BUILD_DIR/.profile.d
+cp "$BUILDPACK_DIR/bin/r_environment.sh" $BUILD_DIR/.profile.d/r_environment.sh
+
+# prevent warnings when building packages
+mkdir -p /app/vendor/R/lib64/R/doc/html
+touch /app/vendor/R/lib64/R/doc/html/R.css
+
+# install dependencies from CRAN
+echo "Executing init.r script" | indent
+
+# set the CRAN mirror and run the init.r program
+/app/vendor/R/bin/R -s <<RPROG > indent
+  Sys.setenv(BUILD_DIR="$BUILD_DIR")
+  setwd("$BUILD_DIR")
+  r <- getOption("repos");
+  r["CRAN"] <- "$CRAN_MIRROR";
+  options(repos=r);
+  `cat $BUILD_DIR/init.r`
+RPROG
+
+echo "R $R_VERSION successfully installed" | indent
+
+# need to copy binaries back so that any installed packages are included in the slug
+cp -R /app/vendor/R/* $VENDOR_DIR/R
+
+ruby compile.rb
